import type { Metadata } from "next";
import React from "react";
import AuthProvider from "@/components/auth-provider";
import LoaderLayout from "@/components/loader-layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`antialiased`}>
          <main className="flex min-h-screen flex-col items-stretch justify-start py-8 px-5 gap-8 bg-slate-400 text-slate-900">
            <LoaderLayout>
              {children}
            </LoaderLayout>
          </main>
        </body>
      </AuthProvider>
    </html>
  );
}
